#! /bin/sh
#__USAGE
#%C	<directory>
#	Extras useful times from HOxP.log in the stated directory.
#	Results might reasonably be redirected to
#	anal/<dir>/lifetimes for use by lifeOH scripts.
#	If the run wraps past 24:00:00, the results may need to
#	be editted by hand.

appname=`basename $0`
function nl_error {
  echo $appname: $* >&2
  exit 1
}
dir=$1
[ -f $dir/HOxP.log ] || nl_error Cannot locate HOxP.log
grep "Online Position" $dir/HOxP.log | cut -c 1-8
echo 48:00:00
