static char paz_dup0[] = "unknown                                           ";
char *Paz_strings[] = {
  "Wait                                              ",
  "Power Mode Ready                                  ",
  "Current Mode Ready                                ",
  "Power Mode Adjust                                 ",
  "Current Mode Adjust                               ",
  "Diode Off, Temperature Ready                      ",
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  "EEPROM Data Read Error                            ",
  "AC Fault > 50ms                                   ",
  "System Boot Marker                                ",
  "Communications Transmission Error                 ",
  "Laser Power Outside Ready Range                   ",
  "Power Mode Adjust Timeout                         ",
  "Passbank Over-temperature                         ",
  "Both Passbanks Current Limited                    ",
  "Diode Module Interlock Test: Bad Voltage          ",
  "Diode Module Interlock Test: Bad Logic            ",
  "Diode Module Safety Check 2: Bad Voltage          ",
  "Diode Module Safety Check 2: Bad Logic            ",
  "Diode Module Safety Check 1: Bad Voltage          ",
  "Diode Module Safety Check 1: Bad Logic            ",
  "Shutter Failed Interlock Safety Test              ",
  "Both Sensors 1 & 2 Failed Shutter Safety Test     ",
  "Sensor 2 Failed Shutter Safety Test               ",
  "Sensor 1 Failed Shutter Safety Test               ",
  "Safety Shutter Open, Should Be Closed             ",
  "Safety Shutter Closed, Should be Open             ",
  "EEPROM Data Not Available During Start-Up         ",
  "EEPROM Fault On Write Condition                   ",
  "Bad Configuration for uP                          ",
  "Compressor Failed Start-up                        ",
  "Heater Failed Start-up Test                       ",
  "Shorted Thermistor 2                              ",
  "Open Thermistor 2                                 ",
  "Shorted Thermistor 1                              ",
  "Open Thermistor 1                                 ",
  "Multiple Errors                                   ",
  "Diode Over Temperature (>3.7C)                    ",
  "Diode Under Temperature (<7.5C)                   ",
  "Current Limit Passbank 2 Active                   ",
  "Current Limit Passbank 1 Active                   ",
  "Interlock Active                                  ",
  "Safety Relay for Diode 2 is Closed, Should be Open",
  "Safety Relay for Diode 2 is Open, Should be Closed",
  "Safety Relay for Diode 1 is Closed, Should be Open",
  "Safety Relay for Diode 1 is Open, Should be Closed",
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0,
  paz_dup0
};
