% consol.m
% consolidate different flights
% for ratio.m
RAT=[RAT rat(j)'];
Measure=[Measure (ho2(j)./oh(j))'];
TIME=[TIME time(j)'];
OH=[OH oh(j)'];
HO2=[HO2 ho2(j)'];
NO=[NO no(j)'];
CO=[CO coal(j)'];
CH4=[CH4 ch4(j)')];
O3=[O3 o3(j)'];
TMM=[TMM tmm(j)'];
PMM=[PMM pmm(j)'];
CLO=[CLO clo(j)'];
NO2=[NO2 no2(j)'];
NOY=[NOY noy(j)'];
CH4=[CH4 ch4al(j)'];
LAT=[LAT latfp(j)'];
LONG=[LONG longfp(j)'];

