function phxattenuatorb(varargin);
% phxattenuatorb( [...] );
% Attenuator Bits
h = ne_dstat({
  'C', 'AtnSt', 7; ...
	'B', 'AtnSt', 5; ...
	'A', 'AtnSt', 4; ...
	'R', 'AtnSt', 3; ...
	'D', 'AtnSt', 2; ...
	'O', 'AtnSt', 1; ...
	'I', 'AtnSt', 0; ...
	'Scan', 'IXStt', 4; ...
	'On', 'IXStt', 5; ...
	'Alt', 'IXStt', 6 }, 'Bits', varargin{:} );
