function phxbb(varargin);
% phxbb( [...] );
% Bellows Bits
h = ne_dstat({
  'C', 'BlwSt', 7; ...
	'B', 'BlwSt', 5; ...
	'A', 'BlwSt', 4; ...
	'R', 'BlwSt', 3; ...
	'D', 'BlwSt', 2; ...
	'O', 'BlwSt', 1; ...
	'I', 'BlwSt', 0; ...
	'Scan', 'IXStt', 0 }, 'Bits', varargin{:} );
