function phxdlt(varargin);
% phxdlt( [...] );
% Dye Laser Temps
h = timeplot({'DHx1T','DHx2T','DLH1T','DLH2T','DLooT','DRs_T'}, ...
      'Dye Laser Temps', ...
      'Temps', ...
      {'Hx1','Hx2','H1','H2','DLoop','Drs'}, ...
      varargin{:} );
