function phxdc(varargin);
% phxdc( [...] );
% Diodes Current
h = timeplot({'RLSD1I','RLSD2I','RLSD1ISP','RLSD2ISP','LTE_I'}, ...
      'Diodes Current', ...
      'Current', ...
      {'1','2','SP1','SP2','LTE\_I'}, ...
      varargin{:} );
