function phxddiode2(varargin);
% phxddiode2( [...] );
% Diodes Diode 2
h = timeplot({'RLSD2T','RLSD2TSP','LSD2T','LHx1T','LHx2T'}, ...
      'Diodes Diode 2', ...
      'Diode2', ...
      {'R2','SP2','2','Hx1','Hx2'}, ...
      varargin{:} );
