function phxdlsp(varargin);
% phxdlsp( [...] );
% Dye Laser Set Point
h = timeplot({'DTETV','DTEST'}, ...
      'Dye Laser Set Point', ...
      'SetPoint', ...
      {'DTETV','DTEST'}, ...
      varargin{:} );
