function phxddt(varargin);
% phxddt( [...] );
% Diodes Diode Temps
h = timeplot({'RLSD1T','RLSD2T','LSD1T','LSD2T','RLSD1TSP','RLSD2TSP','LHx1T','LHx2T'}, ...
      'Diodes Diode Temps', ...
      'DiodeTemps', ...
      {'R1','R2','1','2','SP1','SP2','Hx1','Hx2'}, ...
      varargin{:} );
