function phxdsp(varargin);
% phxdsp( [...] );
% Diodes Set Point
h = timeplot({'LTETV','LTEST'}, ...
      'Diodes Set Point', ...
      'SetPoint', ...
      {'LTETV','LTEST'}, ...
      varargin{:} );
