function phxdlt(varargin);
% phxdlt( [...] );
% Dye Laser Temps
h = timeplot({'DLH1T','DLH2T','DLooT','DRs_T','DHx1T','DHx2T'}, ...
      'Dye Laser Temps', ...
      'Temps', ...
      {'H1','H2','DLoop','Drs','Hx1','Hx2'}, ...
      varargin{:} );
