function phxdltecc(varargin);
% phxdltecc( [...] );
% Dye Laser TEC Current
h = timeplot({'DTE_I'}, ...
      'Dye Laser TEC Current', ...
      'TECCurrent', ...
      {'DTE\_I'}, ...
      varargin{:} );
