function phxdst(varargin);
% phxdst( [...] );
% Data System Temps
h = timeplot({'HD__T','ICC_T','PC__T','PS__T'}, ...
      'Data System Temps', ...
      'Temps', ...
      {'HD\_\_T','ICC\_T','PC\_\_T','PS\_\_T'}, ...
      varargin{:} );
