function phxdd(varargin);
% phxdd( [...] );
% Diodes Diode 1
h = timeplot({'RLSD1T','RLSD1TSP','LSD1T','LHx1T','LHx2T'}, ...
      'Diodes Diode 1', ...
      'Diode1', ...
      {'R1','SP1','1','Hx1','Hx2'}, ...
      varargin{:} );
