function phxetalonlw(varargin);
% phxetalonlw( [...] );
% Etalon Line Width
h = timeplot({'Et_LW'}, ...
      'Etalon Line Width', ...
      'LineWidth', ...
      {'Et\_LW'}, ...
      varargin{:} );
