function phxetalonb(varargin);
% phxetalonb( [...] );
% Etalon Bits
h = ne_dstat({
  'R', 'EtnSt', 3; ...
	'D', 'EtnSt', 2; ...
	'O', 'EtnSt', 1; ...
	'I', 'EtnSt', 0; ...
	'Scan', 'IXStt', 1; ...
	'On', 'IXStt', 2; ...
	'Alt', 'IXStt', 3 }, 'Bits', varargin{:} );
