function phxit(varargin);
% phxit( [...] );
% Inlet Temps
h = timeplot({'Elb_T','Inl_T','WingT','PD__T','PDSkT'}, ...
      'Inlet Temps', ...
      'Temps', ...
      {'Elb\_T','Inl\_T','WingT','PD\_\_T','PDSkT'}, ...
      varargin{:} );
