function phxlabo(varargin);
% phxlabo( [...] );
% Lab Outputs
h = timeplot({'A0SPt','A1SPt','A2SPt','A5SPt','A6SPt'}, ...
      'Lab Outputs', ...
      'Outputs', ...
      {'0','1','2','5','6'}, ...
      varargin{:} );
