function phxlabi(varargin);
% phxlabi( [...] );
% Lab Inputs
h = timeplot({'L12AV','L12BV','L12CV','Lab_1','Lab_2','Lab_3','Lab_6','Lab_7','Lab_8'}, ...
      'Lab Inputs', ...
      'Inputs', ...
      {'12A','12B','12C','1','2','3','6','7','8'}, ...
      varargin{:} );
