function phxlt(varargin);
% phxlt( [...] );
% Laser Temps
h = timeplot({'CIn_T','COutT','LHx1T','LHx2T','LMP_T'}, ...
      'Laser Temps', ...
      'Temps', ...
      {'In','Out','Hx1','Hx2','LMP'}, ...
      varargin{:} );
