function phxlabo(varargin);
% phxlabo( [...] );
% Lab Outputs
h = timeplot({'A0SPt','A1SPt','A2SPt','A3SPt','A4SPt','A5SPt','A6SPt','A7SPt'}, ...
      'Lab Outputs', ...
      'Outputs', ...
      {'0','1','2','3','4','5','6','7'}, ...
      varargin{:} );
