function phxmtm(varargin);
% phxmtm( [...] );
% Misc Temps Mincos
h = timeplot({'HtXT2','PhoT2','DetT2'}, ...
      'Misc Temps Mincos', ...
      'Mincos', ...
      {'HtXT2','PhoT2','DetT2'}, ...
      varargin{:} );
