function phxmtm(varargin);
% phxmtm( [...] );
% Misc Temps Mincos
h = timeplot({'PhoT2','DetT2'}, ...
      'Misc Temps Mincos', ...
      'Mincos', ...
      {'PhoT2','DetT2'}, ...
      varargin{:} );
