function phxnt(varargin);
% phxnt( [...] );
% Nav Temperature
h = timeplot({'TTemp','STemp'}, ...
      'Nav Temperature', ...
      'Temperature', ...
      {'TTemp','STemp'}, ...
      varargin{:} );
