function phxpcp(varargin);
% phxpcp( [...] );
% P Control Pressure
h = timeplot({'SD__P','SD_P2','PV_SetP'}, ...
      'P Control Pressure', ...
      'Pressure', ...
      {'P','P2','Set'}, ...
      varargin{:} );
