function phxpinchb(varargin);
% phxpinchb( [...] );
% Pinch Bits
h = ne_dstat({
  'R', 'PVStat', 3; ...
	'D', 'PVStat', 2; ...
	'O', 'PVStat', 1; ...
	'I', 'PVStat', 0; ...
	'Scan', 'IXStt', 7 }, 'Bits', varargin{:} );
