function phxpcp(varargin);
% phxpcp( [...] );
% P Control Pressure
h = timeplot({'SD_P2','PV_SetP'}, ...
      'P Control Pressure', ...
      'Pressure', ...
      {'SD\_P2','SetPoint'}, ...
      varargin{:} );
