function phxpowervc(varargin);
% phxpowervc( [...] );
% Power 28V_ Current
h = timeplot({'V28I1','V28I2'}, ...
      'Power 28V_ Current', ...
      '28V_Current', ...
      {'V28I1','V28I2'}, ...
      varargin{:} );
