function phxpmtt(varargin);
% phxpmtt( [...] );
% PMT Temps
h = timeplot({'X1DAT','X1FAT','X2DAT','X2FAT'}, ...
      'PMT Temps', ...
      'Temps', ...
      {'1D','1F','2D','2F'}, ...
      varargin{:} );
