#! /bin/sh
#__USAGE
#%C	<date>
# HOXPLOT
# HOx Housekeeping data batch file.
# Created 10/1995
# Modified 6/1996, 4/1997, 10/6/1999
# > input flight day <
# (example: wave 960718)
# 
where=//35/home/hoxp/anal/housekeep
jessica=//41/dos/d/solve/flight
sps2mat -b$where/jumbo2mat.inp
#mkdir $jessica/$1
#mv *.mat $jessica/$1
