% fx0328.m        
%  corrects for failure on beam splitter cube on 930427.   
        n2sig1=n2sig1.*1.35; 
        n2sig2=n2sig2.*0.3;
        dx1sig_hox=dx1sig_hox.*1.35;
        dx2sig_hox=dx2sig_hox.*.67;
        sx1sig_hox=sx1sig_hox.*1.35;
        c2_hox=c2_hox./1.12;
        dx1sig_oh=dx1sig_oh.*1.35;
        dx2sig_oh=dx2sig_oh.*.67;
        c2_oh=c2_oh./1.12;
        dx1sig_no1=dx1sig_no1.*1.35;
        dx1sig_no2=dx1sig_no2.*1.35;
        dx1sig_no3=dx1sig_no3.*1.35;
        dx1sig_no4=dx1sig_no4.*1.35;
        dx1sig_no5=dx1sig_no5.*1.35;
        dx1sig_no6=dx1sig_no6.*1.35;
        dx2sig_no1=dx2sig_no1.*0.67;
        dx2sig_no2=dx2sig_no2.*0.67;
        dx2sig_no3=dx2sig_no3.*0.67;
        dx2sig_no4=dx2sig_no4.*0.67;
        dx2sig_no5=dx2sig_no5.*0.67;
        dx2sig_no6=dx2sig_no6.*0.67;


